# Generated by Django 4.2.1 on 2023-06-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_edu', '0003_administrator_adm_student_stud_teacher_teach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_edu.groups'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_edu.groups'),
        ),
    ]
