# Generated by Django 4.2.1 on 2023-06-01 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_edu', '0004_alter_groupcourse_id_group_alter_lesson_id_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 6, 1, 23, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 6, 1, 23, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='discipine',
            field=models.CharField(default='Math', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='id_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='platform_edu.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
