# Generated by Django 4.2.1 on 2023-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_edu', '0005_lesson_create_date_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(),
        ),
    ]
