# Generated by Django 4.2.1 on 2023-06-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_edu', '0007_administrator_ei_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitution',
            name='courses_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='director',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='groups_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='teachers_list',
            field=models.JSONField(default=dict),
        ),
    ]
