# Generated by Django 4.2.1 on 2023-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_edu', '0008_alter_educationalinstitution_courses_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='ei_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='groups',
            name='courses_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.CharField(),
        ),
    ]
